import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/nav";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body className={inter.className + 'w-full'}>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <Nav />
          <div className="mx-auto container" style={{minHeight: 'calc(100vh - 57px)'}}>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
